# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild Artifact

on:
  push:
    branches: ["main", "Milestone/*"]
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration (Debug/Release/all)'
        required: false
        default: 'Debug'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION_DEBUG: Debug
  BUILD_CONFIGURATION_RELEASE: Release

permissions:
  contents: read

jobs:
  prepare-matrix:
    runs-on: test-self
    outputs:
      configurations: ${{ steps.set-matrix.outputs.configurations }}
    steps:
      - name: Decide configurations
        id: set-matrix
        shell: cmd
        run: |
          IF "%GITHUB_EVENT_NAME%"=="push" (
            echo configurations=["Debug"]>> %GITHUB_OUTPUT%
          ) ELSE (
            IF /I "${{ inputs.configuration }}"=="all" (
              echo configurations=["Debug","Release"]>> %GITHUB_OUTPUT%
            ) ELSE (
              echo configurations=["${{ inputs.configuration }}"]>> %GITHUB_OUTPUT%
            )
          )

  build-and-upload:
    needs: prepare-matrix
    runs-on: test-self

    strategy:
      fail-fast: false
      matrix:
        configuration: ${{fromJson(needs.prepare-matrix.outputs.configurations)}}

    env:
      DOTNET_CLI_UI_LANGUAGE: ja-JP
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
      # NUGET_PACKAGES: ${{ runner.temp }}/nuget-packages

    steps:
      - uses: actions/checkout@v6.0.1

      # - name: Set UTF-8 encoding
      #   run: |
      #     [Console]::OutputEncoding = [System.Text.Encoding]::UTF8

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      # - name: Cache NuGet packages
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ runner.temp }}/nuget-packages
      #     key: ${{ runner.os }}-nuget-${{ hashFiles('**/[Pp]ackages*.config', '**/packages.lock.json', '**/*.props', '**/*.targets') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nuget-

      # - name: Restore NuGet packages
      #   working-directory: ${{env.GITHUB_WORKSPACE}}
      #   run: msbuild /restore

      - name: Build ${{ matrix.configuration }}
        working-directory: ${{env.GITHUB_WORKSPACE}}
        env:
          NUGET_PACKAGES: ${{ runner.temp }}/nuget-packages
        # Add additional options to the MSBuild command line here (like platform or verbosity level).
        # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
        run: |
          chcp 932 >nul
          msbuild /m:8 ^
          /p:Configuration=${{matrix.configuration}} ^
          /p:OutDir="../build/${{matrix.configuration}}/${{matrix.configuration}}" ^
          ${{env.SOLUTION_FILE_PATH}}
        shell: cmd

      - name: Copy Assets and DLL for Artifact
        working-directory: ${{env.GITHUB_WORKSPACE}}
        shell: cmd
        run: |
          IF /I "${{ matrix.configuration }}"=="Debug" (
          xcopy ".\HEW2026_Project\assimp-vc143-mtd.dll" ".\build\Debug\Debug\" /y
          xcopy ".\HEW2026_Project\Assets" ".\build\Debug\Debug\Assets\" /e /i /y
          ) ELSE (
          xcopy ".\HEW2026_Project\assimp-vc143-mt.dll" ".\build\Release\Release\" /y
          xcopy ".\HEW2026_Project\Assets" ".\build\Release\Release\Assets\" /e /i /y
          )

      - name: Calculate Artifact folder name
        id: vars
        shell: cmd
        run: |
          for /f "tokens=*" %%i in ('git rev-parse --short HEAD') do @echo sha_short=%%i>> %GITHUB_OUTPUT%

      - name: Upload Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: HEW2026-Build.${{matrix.configuration}}.${{ github.run_number }}-${{ steps.vars.outputs.sha_short }}
          path: ./build/${{matrix.configuration}}
          retention-days: 3
